### ISSUE TITLE
Проверка ДЗ1 СУБД

### ISSUE THREAD

**Issue by 3kybika** [go-park-mail-ru/2024_2_RPO#9]
- [x] Очень грустно, что начали не со схемы, а с кода :( Надеюсь сильных правко по коду не будет. В проде так, пожалуйста, не надо - сначала проектируем, потом остальное
- [x] Не везде есть created_at, updated_at (да, где-то их отсутствие - уместно, но не всегда) 
- [x] Ограничения на уникальность не везде есть, как и NOT NULL / !=''

**Comment by 3kybika** [comment]
- [ ] Email не должен быть CITEXT - он регистрозависимый
- [ ] А есть какой-то смысл в FILE_TYPE? Почему бы сразу айдишник не вставлять в нужное поле - тогда и картинка переиспользуема если что, и логики никакой не надо дополнительной.
- [ ] Механизма комментариев/чата не планируется?
- [ ]  Сессиии пользователей - в редисе?
- [ ] Хотелось бы увидеть все функциональные зависимости, а не только от первичного ключа. Например:
В табличке User указана: {u_id} -> {nickname, description, joined_at, updated_at, password_hash, email, avatar_file_uuid}
И явно должна быть ФЗ {email} -> {u_id, nickname, description, joined_at, updated_at, password_hash, avatar_file_uuid}

**Comment by DeDxYk594** [comment]
По поводу `FILE_TYPE`: предполагалось, что этот тип нужен, чтобы чистить неиспользумые файлы. Если `FILE_TYPE` есть, надо будет делать удаление для каждого типа (что делает 4 SELECT'а), а если его нет, запрос будет сильно сложнее, потому что нужно будет учитывать данные со всех таблиц

**Comment by DeDxYk594** [comment]
Комментарии и чат - мы прорабатываем модель, к текущему РК это не требуется

**Comment by DeDxYk594** [comment]
Сессии пользователей хранятся в key-value DBMS (Redis), потому что это эффективнее и позволяет разгрузить реляционную СУБД

**Comment by DeDxYk594** [comment]
Механизм миграций (https://pkg.go.dev/github.com/golang-migrate/migrate/v4) подключен, как и сказано в задании
